Revert "circleci - temporary disable no changes script"
This reverts commit 6110425cff6fab5d5a391f4bcf0242e3451e9d3e.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -562,13 +562,13 @@ jobs:
       - run: cd bit && bit cc
       - run: cd bit && bit status
       - run: cd bit && bit diff
-      # - run:
-      #     name: If no component has changed, fail the job
-      #     command: |
-      #       if cd bit && bit diff | grep -q "there are no modified components to diff"; then
-      #         echo "No changes detected, failing job to prevent further workflow execution."
-      #         exit 1
-      #       fi
+      - run:
+          name: If no component has changed, fail the job
+          command: |
+            if cd bit && bit diff | grep -q "there are no modified components to diff"; then
+              echo "No changes detected, failing job to prevent further workflow execution."
+              exit 1
+            fi
       # - run: cd bit && rm -rf node_modules/.bin/bit
       - run: cd bit && npm run generate-cli-reference
       - run: cd bit && npm run generate-cli-reference-json
